### ISSUE TITLE
Logcat format error

### ISSUE THREAD

**Issue by yikwing** [orhanobut/logger#185] opened 2018-04-12 13:26 UTC
- Android studio version:     3.1.1
- Android gradle plugin version:    4.6
- Logger version:    2.2.0
- Emulator/phone information:       oneplus A500

After AS version 3.1.0, Logcat merges logs that have been marked for a short time.

![image](https://user-images.githubusercontent.com/20245290/38680126-2376c800-3e98-11e8-9dea-a0d191597705.png)

**Comment by apkcore** [comment] 2018-04-13 07:32
You can try it, this is address: https://github.com/Blankj/ALog

**Comment by orhanobut** [comment] 2018-04-14 08:03
The issue is related to new version of LogCat unfortunately. There is an open issue for this. We can keep tracking from there. Therefor closing this one. 👍

**Closed by orhanobut** 2018-04-14 08:03 UTC
