### ISSUE TITLE
v1.12 Logger.json  bug

### ISSUE THREAD

**Issue by hzy87email** [orhanobut/logger#65] opened 2016-03-31 06:48 UTC
Process: com.jason.loggertest, PID: 31611
Theme: themes:{}
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.jason.loggertest/com.jason.loggertest.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2450)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510)
    at android.app.ActivityThread.-wrap11(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5461)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
 Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
    at com.orhanobut.logger.LoggerPrinter.json(LoggerPrinter.java:169)
    at com.orhanobut.logger.Logger.json(Logger.java:86)
    at com.jason.loggertest.MainActivity.onCreate(MainActivity.java:18)
    at android.app.Activity.performCreate(Activity.java:6251)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2403)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2510) 
    at android.app.ActivityThread.-wrap11(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1363) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5461) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by carl1990** [comment] 2016-04-05 06:05
I use version 1.12
and add this code `com.orhanobut.logger.Logger.json(content);`
but print nothing in console

**Comment by TokenYc** [comment] 2016-05-12 03:45
I use version 1.3 and print nothing in console when i use logger.json() on some devices.
device is huawei p7

**Comment by orhanobut** [comment] 2017-05-28 11:34
Could you try with version 2.0.0 and reproduce the issue again?

**Comment by orhanobut** [comment] 2017-06-04 12:04
Closing this one due to many changes and seems not valid anymore.

**Closed by orhanobut** 2017-06-04 12:04 UTC
Labels: waiting for reply
