### ISSUE TITLE
Getting Logger to print the name of the  instance class instead of the base class

### ISSUE THREAD

**Issue by androiddev-smartside** [orhanobut/logger#36] opened 2015-07-20 14:06 UTC
I'm getting an issue where, because a lot my classes extend some base class, most of my logs from Logger are reported with the base class name, which is not very helpful.

Please let me know if there's any easy way around this

**Comment by orhanobut** [comment] 2015-07-31 19:06
Can you show the output and the place that you use logger? Current class should be printed regardless of the super class.

**Comment by orhanobut** [comment] 2016-10-25 12:32
Quite an old thread, I hope that this issue is somehow solved since I couldn't reproduce, therefore I'm closing the issue.

**Closed by orhanobut** 2016-10-25 12:32 UTC
Labels: bug
