### ISSUE TITLE
BaseApplication.onCreate  (null:-1)

### ISSUE THREAD

**Issue by xLyong** [orhanobut/logger#149] opened 2017-09-20 09:17 UTC
D: │ Instrumentation.callApplicationOnCreate  (Instrumentation.java:1028)
D: │    BaseApplication.onCreate  (null:-1)

**Comment by orhanobut** [comment] 2018-03-27 12:08
It's not clear what the issue is. Closing this one. Please reopen if you can elaborate it more. Thanks

**Closed by orhanobut** 2018-03-27 12:08 UTC
