### ISSUE TITLE
logger timestamp and tab-delimited

### ISSUE THREAD

**Issue by zorro0799** [orhanobut/logger#99] opened 2016-11-22 10:29 UTC
Thanks to the developer's work, my problem is that I used the adb logcat > d: / XXX. TXT redirected to a file, use logger no timestamp is very convenient, can add a timestamp?
2. Without the tab-delimited time can remove the tab-delimited

**Comment by orhanobut** [comment] 2017-05-28 11:56
@zorro0799 I'm sorry, I didn't understand the issue clearly. Do you need timestamp in logs? Current logcat already contains one though.
Can you elaborate the second part? Thanks

**Comment by orhanobut** [comment] 2017-06-04 12:05
Closing this issue since the issue is not clear.

**Closed by orhanobut** 2017-06-04 12:05 UTC
Labels: waiting for reply
