### ISSUE TITLE
v1.12 Logger.json cause nullpoint exception but v1.11 is OK

### ISSUE THREAD

**Issue by XConstantine** [orhanobut/logger#55] opened 2015-12-22 08:11 UTC
```
public void getBonusData() {
        String url = HttpUrl.CLIST;
        Map<String, String> args = new HashMap<>();
        args.put("type", "1");
        HttpRequest httpRequest = new HttpRequest("CLIST_BONUS");
        httpRequest.postRequest(url, args, new HttpResponse() {
            @Override
            public void onSucceedResponse(String response) {
                Logger.json(response);
            }

            @Override
            public void onErrorResponse(VolleyError error) {
                Logger.t("CLIST_BONUS").d(error.toString());
            }
        });
    }  
```

12-22 16:05:11.341 12284-12284/com.hangzhuangyuan.employee E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: com.hangzhuangyuan.employee, PID: 12284
                                                                             java.lang.NullPointerException
                                                                                 at com.orhanobut.logger.LoggerPrinter.log(LoggerPrinter.java:204)
                                                                                 at com.orhanobut.logger.LoggerPrinter.d(LoggerPrinter.java:110)
                                                                                 at com.orhanobut.logger.LoggerPrinter.json(LoggerPrinter.java:160)
                                                                                 at com.orhanobut.logger.Logger.json(Logger.java:86)
                                                                                 at com.hangzhuangyuan.employee.fragment.BonusFragment$1.onSucceedResponse(BonusFragment.java:52)
                                                                                 at com.hangzhuangyuan.employee.network.HttpRequest$1.onResponse(HttpRequest.java:33)
                                                                                 at com.hangzhuangyuan.employee.network.HttpRequest$1.onResponse(HttpRequest.java:30)
                                                                                 at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:67)
                                                                                 at com.android.volley.toolbox.StringRequest.deliverResponse(StringRequest.java:30)
                                                                                 at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
                                                                                 at android.os.Handler.handleCallback(Handler.java:733)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:136)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:5094)
                                                                                 at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                 at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:702)
                                                                                 at dalvik.system.NativeStart.main(Native Method)

**Comment by orhanobut** [comment] 2015-12-23 08:52
I'll compare this 2 version, .json method was written in a rush, I may need to make more condition checks.

**Comment by bluejamesbond** [comment] 2016-01-02 10:34
+1

**Comment by hrskrs** [comment] 2016-02-16 10:21
I didnt see any difference that will affect this issue between those versions. Probably in one version you got non null result as a response, and in the other one you got null. The only way i succeded to reproduce this issue was by giving `null` as a parameter when logging.

**Comment by ben-manes** [comment] 2016-03-07 22:09
Just hit this due to refactoring some native code and accidentally generating invalid json (missing comma).

**Comment by orhanobut** [comment] 2017-05-28 11:33
This should be fixed with the latest versions.

**Closed by orhanobut** 2017-05-28 11:33 UTC
Labels: bug
